# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-IEFavorites
version:      0.03
version_from: lib/Win32/IEFavorites.pm
installdirs:  site
requires:
    DateTime:                      0
    File::Find::Rule:              0
    File::Spec:                    0
    Win32::FileTime:               0
    Win32::TieRegistry:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
