---
abstract: "handles Internet Explorer's Favorites"
author:
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-IEFavorites
no_index:
  directory:
    - t
    - inc
requires:
  Config::IniFiles: 0
  DateTime: 0
  File::Find::Rule: 0
  File::Spec: 0
  Win32::FileTime: 0
  Win32::TieRegistry: 0
version: 0.06
